apiVersion: apps/v1
kind: Deployment
metadata:
  name: 101-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: cbabu85/k8s-demo:latest
        name: web-ctr
        ports:
        - containerPort: 8080
